417 League 1 code
SwerveRoboticsTeams/FtcRobotController pull request #17
Opened 2021-11-28 05:01 UTC by knguyen-hub

Before issuing a pull request, please see the contributing page.

2021-11-29 00:17 UTC, malavika1 requested changes

2021-11-29 00:17 UTC, malavika1 commented on .idea/jarRepositories.xml
> +    <remote-repository>
What is all this?

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/AutonomousCompetition.java
> +@Autonomous(name = "Auto Freight")
Should this name match the file name?

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/AutonomousCompetition.java
> +
You shouldn't have a blank line before a }

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/AutonomousCompetition.java
> +
You shouldn't have a blank line before a }

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/AutonomousCompetition.java
> +            //sleep(5000);
No commented out code

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/AutonomousCompetition.java
> +
No blank line here

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/AutonomousCompetition.java
> +
No blank lines here

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/BarcodeDetectionOpenCV.java
> +
You shouldn't have a blank line after a {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/BarcodeDetectionOpenCV.java
> +
You shouldn't have a blank line after a {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/BarcodeDetectionOpenCV.java
> +        if (x < 163) {
These magic numbers should be constants

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/BarcodeDetectionOpenCV.java
> +
No blank line here

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/DuckParkingAuto.java
> +
No blank lines here

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +            if (Math.abs(pivotSpeed)> maxSpeed){
You should have spaces around >

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +
No blank line before }

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +        } while ((Math.abs(errorAngle) > angleTolerance || Math.abs(errorDistance) > distanceTolerance) && opModeIsActive() );
No space before the ) at the end

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +        motorFR.setPower(0);
A blank line before this would be cleaner looking

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +            angleToTarget = Math.atan2(errorX, errorY); // switched for testing
Should this still be switched?

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +        else if (angle < -180) {
The else if should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +
No blank line here

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterOpMode.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterOpMode.java
> +    static final int SHOULDER_CAP = 0; // todo get correct values
Did you do this yet? Remove this comment once it's done

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterOpMode.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterOpMode.java
> +
No blank line before }

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterOpMode.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterOpMode.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterOpMode.java
> +
No blank lines before }

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterOpMode.java
> +
No blank line before }

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterTeleOp.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterTeleOp.java
> +
No blank line before }

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterTeleOp.java
> +
No blank lines before }

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Parking.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/FIRFilter.java
> +{
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Filter.java
> +{
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +{
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +
You shouldn't have multiple blank lines in a row

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +
You shouldn't have multiple blank lines in a row

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +    public void reset(){
There should be a space between ) and {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Polynomial.java
> +
You don't need this blank line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Polynomial.java
> +{
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Polynomial.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Polynomial.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Polynomial.java
> +
No blank lines before }

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +
No blank line here

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +{
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +
No blank line here

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        for (int i = 0; i < list.length; i++ )
No space between + and )

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        for (int i = 0; i < list.length; i++ )
No space between + and )

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +
You shouldn't have multiple blank lines in a row

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        for (int i = 0; i < array.length; i++ )
No space between + and )

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        for (int i = (array.length - 2); i >= 0; i-- )
No space between - and )

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        for (int i = 0; i < (array.length - 2); i++ )
No space between + and )

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        for(int i = 0; i < size - 1; i++ )
No space between + and )

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        for(int i = 0; i < size - 1; i++ )
No space between + and )

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        for(int i = 0; i < size; i++ )
No space between + and )

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +
No blank line before }

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Toggler.java
> +    {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Toggler.java
> +        if(press)
No commented out code

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Toggler.java
> +        {
This curly brace should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Robot.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Robot.java
> +    public void setCorrectedHeading(double initialHeading) {
You should have a blank line before a new method

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/TeleOpCompetition.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/TeleOpCompetition.java
> +
No blank lines before }

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/TestTeamElementOpenCVDetection.java
> +
You shouldn't have multiple blank lines in a row

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/TestTeamElementOpenCVDetection.java
> +
No blank line after {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/TestTeamElementOpenCVDetection.java
> +            if (barcodeDetector.barcodeIndex == 0){
Add space between ) and {

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/TestTeamElementOpenCVDetection.java
> +            else if (barcodeDetector.barcodeIndex == 1){
The else if should be on the previous line

2021-11-29 00:17 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/TestTeamElementOpenCVDetection.java
> +            telemetry.addData("contours length", barcodeDetector.contours.size());
It would be cleaner if there was a blank line before this

2021-12-01 01:23 UTC, knguyen-hub commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterOpMode.java
> +    static final int SHOULDER_CAP = 0; // todo get correct values
Not yet, was hoping to get it done this meeting or next

2021-12-21 18:59 UTC, malavika1 requested changes

2021-12-21 18:59 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/AutoTest.java
> +        */
No commented out code

2021-12-21 18:59 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/AutoTest.java
> +
No commented out code

2021-12-21 18:59 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightAuto.java
> +        //wristServo.setPosition(0.0);
No commented out code

2021-12-21 18:59 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightAuto.java
> +        //
You shouldn't have an empty comment. This can just be a blank line.

2021-12-21 18:59 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightAuto.java
> +
You shouldn't have multiple blank lines in a row.

2021-12-21 18:59 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightAuto.java
> +
No blank lines before a }

2021-12-21 18:59 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightWarehouseSideAuto.java
> +    }
This function should be in a shared base class.

2021-12-21 18:59 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterTeleOp.java
> +
No multiple blank lines in a row

2021-12-21 18:59 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterTeleOp.java
> +
No commented out code

2022-01-26 19:46 UTC, malavika1 requested changes

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +            if (x < 213 - offset) { // prob need to decrease
```suggestion
            }
            
            if (x < 213 - offset) { // prob need to decrease
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +            if (x < 213 - offset) { // prob need to decrease
Did you actually decrease it?

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +            //barcodeIndex = barcodeDetector.index;
No commented out code

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +
No blank line here

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +
No blank line here

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +                telemetry.addLine(" ");
Why are you adding a space to the telemetry?

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +
No blank lines

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +
No blank line after {

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +
No blank line before }

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +            // go back
```suggestion
            moveAtAngle(-26, 0.7, 90 * allianceSide);
            
            // go back
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +            // go back
```suggestion
            moveAtAngle(-24, 0.7, 90 * allianceSide);
            
            // go back
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +            // moveInches(10, 0.7);
No commented out code

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +            while (shoulderMotor.isBusy() || elbowMotor.isBusy()) {
```suggestion
            runMotorToPosition(elbowMotor, ELBOW_LEVEL_1, 0.5);
            
            while (shoulderMotor.isBusy() || elbowMotor.isBusy()) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +            moveAtAngle(28, 0.7, 90 * allianceSide);
```suggestion
            runMotorToPosition(elbowMotor, ELBOW_LEVEL_2, 0.5);
            
            while (shoulderMotor.isBusy() || elbowMotor.isBusy()) {
                telemetry.addLine(" ");
            }
            
            moveAtAngle(28, 0.7, 90 * allianceSide);
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +            moveAtAngle(31, 0.7, 90 * allianceSide);
```suggestion
            runMotorToPosition(elbowMotor, ELBOW_LEVEL_3, 0.5);
            
            while (shoulderMotor.isBusy() || elbowMotor.isBusy()) {
                telemetry.addLine(" ");
            }
            
            moveAtAngle(31, 0.7, 90 * allianceSide);
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +            // go back
```suggestion
            moveAtAngle(-27, 0.7, 90 * allianceSide);
            
            // go back
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +        else if (allianceSide == -1) {
```suggestion
        } else if (allianceSide == -1) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/CarouselAuto.java
> +    public void blueDeliverDuck () throws InterruptedException {
```suggestion
    }
    
    public void blueDeliverDuck () throws InterruptedException {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightAuto.java
> +                if (x < 213 - offset) { // prob need to decrease
```suggestion
                }
                
                if (x < 213 - offset) { // prob need to decrease
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightAuto.java
> +            //barcodeIndex = barcodeDetector.index;
No commented out code

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightAuto.java
> +            // 15 for level 3
What is this referring to?

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightAuto.java
> +        //pivot(90, 0.5);
No commented out code

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightAuto.java
> +       moveInches(78, 1.0);
This doesn't line up

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightWarehouseSideAuto.java
> +        // set up detection
It might be helpful to have a shared method for setting up detection since it happens multiple times.

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightWarehouseSideAuto.java
> +
No multiple blank lines in a row

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightWarehouseSideAuto.java
> +                if (x < 213 - offset) { // prob need to decrease
```suggestion
                }
                
                if (x < 213 - offset) { // prob need to decrease
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/FreightWarehouseSideAuto.java
> +            // THIS MOVEMENT VARIES I THINK
Did you verify this?

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +        while ((Math.abs(errorAngle) > 3 || Math.abs(errorDistance) > distanceTolerance) && opModeIsActive());
```suggestion
        } while ((Math.abs(errorAngle) > 3 || Math.abs(errorDistance) > distanceTolerance) && opModeIsActive());
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +        //double targetAngle = robot.getCorrectedHeading();
No commented out code

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterAutonomous.java
> +        motorFR.setPower(0);
```suggestion
        } while ((Math.abs(errorAngle) > 3 || Math.abs(errorDistance) > distanceTolerance) && opModeIsActive());
        
        motorFR.setPower(0);
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterOpMode.java
> +    static final double GRABBER_IN = 0.75;
```suggestion
    // arm and grabber constants
    static final double GRABBER_IN = 0.75;
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterOpMode.java
> +        motorBR.setDirection(DcMotor.Direction.FORWARD); // todo reverse back
Is this done?

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterTeleOp.java
> +        else if (gamepad2.y) {
```suggestion
        } else if (gamepad2.y) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterTeleOp.java
> +        if ((Math.abs(shoulderTarget - shoulderMotor.getCurrentPosition()) <= 5 && movingShoulder)
Should this be an else if?

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/MasterTeleOp.java
> +        if (Math.abs(elbowTarget - elbowMotor.getCurrentPosition()) >= 5 && movingElbow) {
Should this be an else if?

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/FIRFilter.java
> +{
```suggestion
public class FIRFilter implements Filter {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/FIRFilter.java
> +    {
```suggestion
    public FIRFilter(double[] w) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/FIRFilter.java
> +    {
```suggestion
    public FIRFilter(Polynomial func, int depth) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/FIRFilter.java
> +    {
```suggestion
    public void roll(double newValue) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/FIRFilter.java
> +    {
```suggestion
    public double getFilteredValue() {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Filter.java
> +{
```suggestion
public interface Filter {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +{
```suggestion
public class PIDFilter implements Filter {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +    {
```suggestion
    public PIDFilter(double P, double I, double D) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +    {
```suggestion
    public void roll(double newValue) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +    {
```suggestion
    public double getFilteredValue() {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/PIDFilter.java
> +    public void reset(){
```suggestion
    // This clears any residual values in our PID loop
    public void reset() {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Polynomial.java
> +{
```suggestion
*/
public class Polynomial {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Polynomial.java
> +    {
```suggestion
    public Polynomial(double[] c) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Polynomial.java
> +    {
```suggestion
    public double getOuput(double input) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Polynomial.java
> +        {
```suggestion
        for (int i = 0; i < size; i++) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    // Return all the values of a 1D array added together
```suggestion
*/
public abstract class SequenceUtilities {
    // Return all the values of a 1D array added together
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
```suggestion
    public static double sum(double[] list) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
```suggestion
        for (int i = 0; i < list.length; i++) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
```suggestion
    public static double[] scalarMultiply(double[] list, double factor) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
```suggestion
        for (int i = 0; i < list.length; i++) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
```suggestion
    public static double average(double[] array) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
```suggestion
    public static double weightedAverage(double[] array, double[] w) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
```suggestion
        for (int i = 0; i < array.length; i++) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
```suggestion
    public static double[] roll(double[] array, double newValue) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
```suggestion
        for (int i = (array.length - 2); i >= 0; i--) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
```suggestion
    public static double[] rollReversed(double[] array, double newValue) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
```suggestion
        for (int i = 0; i < (array.length - 2); i++) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        array[array.length - 1] = newValue;
```suggestion
        }
        
        array[array.length - 1] = newValue;
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
```suggestion
    public static double getLargestValue(double[] array) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
```suggestion
        for (int i = 0; i < size - 1; i++) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
```suggestion
    public static double getLargestMagnitude(double[] array) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
```suggestion
        for (int i = 0; i < size - 1; i++) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
```suggestion
    public static double[] vectorAdd(double[] a, double[] b) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
```suggestion
        for (int i = 0; i < size; i++) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +    {
```suggestion
    public static double[] arrayFromPolynomial(int start, int end, Polynomial func) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/SequenceUtilities.java
> +        {
```suggestion
        for (int i = start; i < end; i++) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Toggler.java
> +    {
```suggestion
    public boolean toggle(boolean button) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Toggler.java
> +    }
```suggestion
    public Toggler() {
    }
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Resources/Toggler.java
> +        {
```suggestion
        if (!prevState && button) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Robot.java
> +    double curAngle = 0;
```suggestion
public class Robot {
    double curAngle = 0;
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Robot.java
> +    }
```suggestion
    public Robot(MasterOpMode masterOpMode) {
        master = masterOpMode;
    }
    
    public void setInitialAngle() {
        initialHeading = master.imu.getAngularOrientation().firstAngle;
    }
    
    public double getInitialHeading() {
        return initialHeading;
    }
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Robot.java
> +    public void setCorrectedHeading(double initialHeading) {
```suggestion
    public double getCorrectedHeading() {
        return master.imu.getAngularOrientation().firstAngle - initialHeading;
    }
    
    public void setCorrectedHeading(double initialHeading) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/Robot.java
> +        // todo Properly account for this factor
Did you do this?

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/TeleOpCompetition.java
> +    @Override
```suggestion
public class TeleOpCompetition extends MasterTeleOp {
    @Override
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/TeleOpCompetition.java
> +        while (opModeIsActive()) {
```suggestion
        robot.setInitialAngle();

        while (opModeIsActive()) {
```

2022-01-26 19:46 UTC, malavika1 commented on Team417_2021/src/main/java/org/firstinspires/ftc/team417_2021/TeleOpCompetition.java
> +    }
```suggestion
        }
    }
```

2022-05-29 19:13 UTC, merged