League two
SwerveRoboticsTeams/FtcRobotController pull request #19
Opened 2021-12-19 21:18 UTC by AbhinavAkkiraju

Final league two code

2021-12-21 04:05 UTC, tmicro requested changes

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/AutonomousCompetition.java
> +package org.firstinspires.ftc.team6220_2021;
This file does not seem to do anything in autonomous.  Consider deleting it.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
> +                tfod.activate();
Tensoflow was already activated on line 43, and the zoom was already set on line 44.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
> +        if (opModeIsActive()) {
This line adds no value to your program, since it only gets executed once at the very beginning of autonomous, with 30 seconds left to go.  Please delete it.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
> +            while (opModeIsActive()) {
This line adds no value to your program, since it only gets executed once at the very beginning of autonomous, with 30 seconds left to go.  opModeIsActive() would always be true at the start of autonomous.  Please delete it.  You should check for opModeIsAcive() before every step in autonoumous, not just at the beginning.

You should not have a loop here, since autonomous only executes a sequence of actions once.  Loops are required for tele-op.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
> +                        // todo
Please change the // todo comments to something more meaningful.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
> +                switch (barcode) {
The code for all 3 cases are very similar.  You should consider re-grouping your code so that similar blocks of code are written once.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/GyroTest.java
> +public class GyroTest extends LinearOpMode
You should extend from MasterOpMode class, and reuse its Initialize() method.  Generally, you should not duplicate your code.  You should write it once, test it once, and reuse it over and over again.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/GyroTest.java
> +        motorBackLeft = hardwareMap.dcMotor.get("motorBackLeft");
you should reuse the Initialize() method in MasterOpMode.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/MasterOpMode.java
>      public void Forward(double DriveInches, double power) {
You should not reverse the right motors on line 81 and 83, and then set negative target positions on lines 105 and 106.  That is confusing and can lead to errors.  Motor reversal should only be done in the Initialize() method in MasterOpMode class.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/ParkStorageUnit.java
>  package org.firstinspires.ftc.team6220_2021;
delete this unused file.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RealBlueDuck.java
>  package org.firstinspires.ftc.team6220_2021;
delete this unused file

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedAutonomousCompetition.java
> +package org.firstinspires.ftc.team6220_2021;
Please see my comments for BlueAutonomousCompetition.java file regarding duplicating tensorflow initialization, and unnecessary opModeIsActive() while loop.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueParkBlockPLaceLeague2.java
>      DcMotor motorBackLeft;
You should not define your motors here.  They should already be defined in MasterOpMode.  Don't define them more than once.  Don't reverse motors here.  Reverse them once, and stick to the same convention throughout all programs.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/Park.java
>      DcMotor motorBackLeft;
You should not define your motors here.  They should already be defined in MasterOpMode.  Don't define them more than once.  Don't reverse motors here.  Reverse them once, and stick to the same convention throughout all programs.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedParkBlockPLaceLeague2.java
>      DcMotor motorBackLeft;
You should not define your motors here.  They should already be defined in MasterOpMode.  Don't define them more than once.  Don't reverse motors here.  Reverse them once, and stick to the same convention throughout all programs.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedParkBlockPLaceLeague2.java
> +public class RedParkBlockPLaceLeague2 extends MasterOpMode{
Why doesn't this file extend from MasterAutonomous class instead of MasterOpMode class?

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedParkBlockPlace.java
> +package org.firstinspires.ftc.team6220_2021;
delete this unused file

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/TeleOpComp.java
>      DcMotor motorFrontLeft;
You should not define your motors here.  They should already be defined in MasterOpMode.  Don't define them more than once.  Don't reverse motors here.  Reverse them once, and stick to the same convention throughout all programs.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/TestClasses/TeleOpTest.java
> +        if (opModeIsActive()) {
delete this unnecessary line.

2021-12-21 04:05 UTC, tmicro commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/TickTest.java
> +        motorBackLeft = hardwareMap.dcMotor.get("motorBackLeft");
You should not define your motors here.  They should already be defined in MasterOpMode.  Don't define them more than once.  Don't reverse motors here.  Reverse them once, and stick to the same convention throughout all programs.

2021-12-21 19:10 UTC, malavika1 commented
We probably shouldn't be checking in the binary file FtcRobotController/src/main/assets/model_20211128_184150.tflite

2021-12-21 19:33 UTC, malavika1 requested changes

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/AutonomousCompetition.java
> +//                }
No commented out code

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
> +            "38Kaaqnu3DABLRXRjSJ1QRSHmE8mIur5Dk3OcqMv3fwTNt5CnhC2J/D5biVGixUQ+dveylNEVNmp0k";
Consider putting some of these constants that are used in multiple files in the MasterAutonomous base class. Then they can be used in all the files without being copy pasted.

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
> +
No multiple blank lines in a row

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueFullAuto.java
> +public class BlueFullAuto extends MasterOpMode{
Shouldn't this extend MasterAutonomous?

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueFullAuto.java
> +        motorArm.setMode(DcMotor.RunMode.RUN_TO_POSITION);
Isn't a lot of this initialization stuff already set somewhere else?

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueFullAuto.java
> +        if (Detection == 1){
space between ) and {

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueFullAuto.java
> +        } else if (Detection == 2){
space between ) and {

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueFullAuto.java
> +        } else if (Detection == 3){
space between ) and {

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueFullAuto.java
> +        Forward(10,0.3);
You should have a space after a comma

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueFullAuto.java
> +        TurnAngle(-125);
You seem to have some inconsistent capitalization conventions.

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueParkBlockPlace.java
> +@Autonomous(name = "BlueBlockPlace_notusing_", group = "Autonomous")
If you're not using it, should it be deleted?

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/GyroTest.java
> +//@Disabled
No commented out code

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/MasterAutonomous.java
> +    }
You can simplify this

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/MasterAutonomous.java
> +        motorBackRight.setPower(-rightSidePower);
Shouldn't you have reversed motors to handle this?

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/MasterAutonomous.java
> +            }*/
No commented out code

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/MasterOpMode.java
> +
Why is this empty?

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/NewHardwareTest.java
> +
No multiple blank lines in a row

2021-12-21 19:33 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/NewHardwareTest.java
> +//        motorBelt.setMode(DcMotor.RunMode.RUN_TO_POSITION);
No commented out code

2021-12-22 19:24 UTC, malavika1 requested changes

2021-12-22 19:24 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/Park.java
> +@Autonomous(name = "ParkWarehouse", group = "Autonomous")
Should this match the file name?

2021-12-22 19:24 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedParkBlockPLaceLeague2.java
> +public class RedParkBlockPLaceLeague2 extends MasterOpMode{
You can probably just call this RedParkBlockPlace

2021-12-22 19:29 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/MasterAutonomous.java
> +        Arrays.sort(array);
Sorting an array is a very expensive way to get the max. Try to find something simpler.

2021-12-27 23:52 UTC, malavika1 requested changes

2021-12-27 23:52 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
> +    private static final String VUFORIA_KEY = Constants.VUFORIA_KEY;
You can probably directly use the constants instead of creating new constants for them.

2021-12-27 23:52 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedParkBlockPlace.java
> +            "38Kaaqnu3DABLRXRjSJ1QRSHmE8mIur5Dk3OcqMv3fwTNt5CnhC2J/D5biVGixUQ+dveylNEVNmp0k";
This should use the new constants or you can delete the file if it's not being used

2022-01-04 05:04 UTC, tmicro approved these changes

2022-01-04 05:16 UTC, merged