League3
SwerveRoboticsTeams/FtcRobotController pull request #20
Opened 2022-01-26 00:31 UTC by satkab

Merging League3 (interleague) branch into Teams (main) branch

2022-01-26 18:46 UTC, malavika1 requested changes

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
>          // todo - distance to carousel
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
>          // todo - distance before turning to the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
>                  // todo - distance to the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
>                  // todo - distance to the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
>                  // todo - distance to the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
>                  // todo - distance backing up from the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
>                  // todo - distance backing up from the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueAutonomousCompetition.java
>                  // todo - distance backing up from the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueLeftAuto.java
> +                        } else if (TSELocation > 533.0 && TSELocation <= 800.0) {
You should use constants for these magic numbers

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueRightAuto.java
> +                        } else if (TSELocation > 533.0 && TSELocation <= 800.0) {
You should use constants for these magic numbers.

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueRightAuto.java
> +    }
Don't you have these methods somewhere else that you can reuse?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedAutonomousCompetition.java
>                  // todo - distance to the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedAutonomousCompetition.java
>                  // todo - distance to the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedAutonomousCompetition.java
>                  // todo - distance to the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedAutonomousCompetition.java
>                  // todo - distance backing up from the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedAutonomousCompetition.java
>                  // todo - distance backing up from the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedAutonomousCompetition.java
>                  // todo - distance backing up from the shipping hub
Is this still a todo or is it done?

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedLeftAuto.java
> +                        } else if (TSELocation > 533.0 && TSELocation <= 800.0) {
You should use constants for these magic numbers

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedLeftAuto.java
> +    }
These methods shouldn't be copy pasted. Reuse them.

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedRightAuto.java
> +public class RedRightAuto extends MasterAutonomous {
A lot of these seem very similar. You should refactor to reuse as much code as possible.

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/TeleOpComp.java
> +                    else {
These should be on the same line
```suggestion
                    } else {
```

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/TeleOpComp.java
> +            else if (gamepad2.b){
```suggestion
            } else if (gamepad2.b) {
```

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/TeleOpComp.java
>                  while (true) {
It's generally bad practice to use a while true loop. Try to avoid it if you can.

2022-01-26 18:46 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/TeleOpCompetition.java
> +// actually fix the left grabber paddle this time !!!!
You can probably delete these comments

2022-01-28 02:34 UTC, malavika1 approved these changes

2022-01-28 02:34 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueLeftAuto.java
> +                    if (recognition.getLabel().equals("TSE")) {
What does TSE stand for?

2022-01-28 02:34 UTC, malavika1 commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/RedLeftAuto.java
> +    @SuppressLint("DefaultLocale")
What does this do?

2022-01-28 02:38 UTC, aniduder commented on Team6220_2021/src/main/java/org/firstinspires/ftc/team6220_2021/BlueLeftAuto.java
> +                    if (recognition.getLabel().equals("TSE")) {
team shipping element

2022-01-28 02:38 UTC, merged